### ISSUE TITLE
Error with .getbindingAccessors

### ISSUE THREAD

**Issue by jlaustill** [knockout/tko#10]
I decided to drop tko into my intranet, by far the biggest project I've used knockout on.  I got surprisingly few errors from what I was expecting.  But one that repeats is this one.  

```
Uncaught Error: 
SyntaxError Expected ':' but got '=' of 
   'click':function(){window.location.href ='/#/Forum/Details?terms='+ encodeURIComponent($root.terms.peek());}
                                        _/ 🔥 \_


    at Parser.parse (http://local.north40net.com/node_modules/tko/dist/ko.js:4069:23)
    at Provider.getBindingAccessors (http://local.north40net.com/node_modules/tko/dist/ko.js:4197:25)
    at computed.disposeWhenNodeIsRemoved (http://local.north40net.com/node_modules/tko/dist/ko.js:4802:98)
    at Function.evaluateImmediate_CallReadThenEndDependencyDetection (http://local.north40net.com/node_modules/tko/dist/ko.js:2667:105)
    at Function.evaluateImmediate_CallReadWithDependencyDetection (http://local.north40net.com/node_modules/tko/dist/ko.js:2639:31)
    at Function.evaluateImmediate (http://local.north40net.com/node_modules/tko/dist/ko.js:2603:20)
    at computed (http://local.north40net.com/node_modules/tko/dist/ko.js:2464:30)
    at applyBindingsToNodeInternal (http://local.north40net.com/node_modules/tko/dist/ko.js:4800:33)
    at applyBindingsToNodeAndDescendantsInternal (http://local.north40net.com/node_modules/tko/dist/ko.js:4590:35)
    at applyBindingsToDescendantsInternal (http://local.north40net.com/node_modules/tko/dist/ko.js:4572:11)Parser.parse
 @ ko.js:4069getBindingAccessors
 @ ko.js:4197computed.disposeWhenNodeIsRemoved
 @ ko.js:4802evaluateImmediate_CallReadThenEndDependencyDetection
 @ ko.js:2667evaluateImmediate_CallReadWithDependencyDetection
 @ ko.js:2639evaluateImmediate
 @ ko.js:2603computed
 @ ko.js:2464applyBindingsToNodeInternal
 @ ko.js:4800applyBindingsToNodeAndDescendantsInternal
 @ ko.js:4590applyBindingsToDescendantsInternal
 @ ko.js:4572applyBindingsToNodeAndDescendantsInternal
 @ ko.js:4599applyBindingsToDescendantsInternal
 @ ko.js:4572applyBindingsToNodeAndDescendantsInternal
 @ ko.js:4599applyBindingsToDescendantsInternal
 @ ko.js:4572applyBindingsToNodeAndDescendantsInternal
 @ ko.js:4599applyBindingsToDescendantsInternal
 @ ko.js:4572applyBindingsToNodeAndDescendantsInternal
 @ ko.js:4599applyBindingsToDescendantsInternal
 @ ko.js:4572applyBindingsToNodeAndDescendantsInternal
 @ ko.js:4599applyBindingsToDescendantsInternal
 @ ko.js:4572applyBindingsToNodeAndDescendantsInternal
 @ ko.js:4599applyBindings
 @ ko.js:4912(anonymous function)
 @ ko.js:6286invokeForEachNodeInContinuousRange
 @ ko.js:6237activateBindingsOnContinuousNodeArray
 @ ko.js:6284executeTemplate
 @ ko.js:6331computed.disposeWhen
 @ ko.js:6373evaluateImmediate_CallReadThenEndDependencyDetection
 @ ko.js:2667evaluateImmediate_CallReadWithDependencyDetection
 @ ko.js:2639evaluateImmediate
 @ ko.js:2603evaluatePossiblyAsync
 @ ko.js:2569notifySubscribers
 @ ko.js:1743valueHasMutated
 @ ko.js:1899Observable
 @ ko.js:1865(anonymous function)
 @ knockout-amd-helpers.js:189execCb
 @ require.js:1693check
 @ require.js:881(anonymous function)
 @ require.js:1136(anonymous function)
 @ require.js:134(anonymous function)
 @ require.js:1186each
 @ require.js:59emit
 @ require.js:1185check
 @ require.js:936enable
 @ require.js:1173init
 @ require.js:786(anonymous function)
 @ require.js:979(anonymous function)
 @ require.js:134(anonymous function)
 @ require.js:1186each
 @ require.js:59emit
 @ require.js:1185check
 @ require.js:936enable
 @ require.js:1173init
 @ require.js:786(anonymous function)
 @ require.js:1011(anonymous function)
 @ require.js:134finishLoad
 @ text.js:169(anonymous function)
 @ text.js:205xhr.onreadystatechange
 @ text.js:317
```

It seems to me that it is returning improperly escaped strings maybe?  It's complaining about this binding
'click':function(){window.location.href ='/#/Forum/Details?terms='+ encodeURIComponent($root.terms.peek());}

And it seems to me if the value was quoted and properly escaped this wouldn't be a syntax error.  But I could be missing something else, so I included the entire call stack, and I'm up for any suggestions on how to debug this further.

Here's the relevant html
```html
<ul class="dropdown-menu">
                        <li data-bind="click: function() {window.location.href = '/#/Forum/Details?terms=' + encodeURIComponent($root.terms.peek());}">
                            Search Forums
                        </li>
                    </ul>
```

**Comment by brianmhunt** [comment]
Awesome!

Unfortunately we don't have a native JavaScript compiler anymore - so some code in data-bind strings will not work.

Fortunately the workarounds are easy in this case.  You can change the binding to

1. `on.click: window.href. ...` or
2. `click: => window.href. ...`

Ie change the function to an "on" event binding, or to a lambda.  (Incidentally the above options should be identical - except the on.click option is backwards-compatible with ko 3.x and punches).

Sorry the parser in tko doesn't handle the function call - it's definitely one of the legacy issues that would be nice to have a work around for.

I will think about it for the next alpha since I think this will be a common issue.

**Comment by jlaustill** [comment]
As time has gone on, I have actually started second guessing how to use these bindings.  I've started moving them all to functions internal to my viewmodels, like this
```html
<li data-bind="click: goToSearch"></li>
```
and moving the code to my viewmodel like
```javascript
var goToSearch = function () {
    window.location.href = '/#/Forum/Details?terms=' + encodeURIComponent(appVM.terms.peek());
}
```
Would this work in tko?  Or would I still need to use the on.click or the arrow function?  I'll play with it and see what I come up with.  I'm not a fan of putting javascript like this in the dom anymore at all.  I wrote this code when I was first figuring knockout out.

**Comment by brianmhunt** [comment]
Yeah tko should work exactly like ko for the function references on the view models (or binding context or options.globals/window)

The hope is that tko will encourage moving away from (complex) code in the dom.

**Comment by jlaustill** [comment]
So this worked for this binding, then I ran into another one where I need to pass in a parameter.  Basically, it's a paging binding that adds first, back, 1, 2, 3, 4, 5, next, last buttons.  My binding looks like this 
```html
data-bind="click: function () {goToPage(pg)}"
```
and that pg is simply a number.  How in TKO should I pass in that paramter if I can't use a function literal?  Will it support the .bind syntax?  Or is there a totally new way to go about it?  This has actually been one of the most frustrating parts of ko since I started using it.  It seems super common to build lists with a foreach and want to call a function with either an index value or a value from the object, such as userId, or postId, messageId, etc etc.  I'm all up for a better way to handle these...

**Comment by brianmhunt** [comment]
Try this:

```html
data-bind="click: => goToPage(pg)"
```

**Comment by jlaustill** [comment]
Ok, I like this syntax!  If it's one of the only non backward compatible issues, I think I could live with it.  It only took me about 15 minutes to go through my entire intranet and search and replace all of these.  And boy does it look cleaner!

I think that closes this issue, onto new ones :)

**Comment by brianmhunt** [comment]
:cake:!
