### ISSUE TITLE
Uncaught TypeError: Cannot read property 'lookup' of undefined

### ISSUE THREAD

**Issue by tresayle** [knockout/tko#100]
### This is my code:

![code](https://user-images.githubusercontent.com/47453366/57847061-d6620c00-77d5-11e9-8357-3dca4c1c2a2e.png)

```HTML
<input type="checkbox" class="setting" data-bind="checked: $parent.Settings.values[value], attr: { id: value }">
```

### This is my error: 

> Uncaught TypeError: Cannot read property 'lookup' of undefined

This part gives the error: `... values[value] ...`. I tried with `values.value`, but if a `value` contains `'-'` it doesn't work.

### Full error

```
Uncaught TypeError: Cannot read property 'lookup' of undefined
    at e.get_value (tko.js:1)
    at Function.e.value_of (tko.js:1)
    at e.set_value (tko.js:1)
    at value (tko.js:1)
    at valueAccessor (tko.js:1)
    at r (tko.js:1)
    at HTMLInputElement.<anonymous> (tko.js:1)
e.get_value @ tko.js:1
e.value_of @ tko.js:1
e.set_value @ tko.js:1
value @ tko.js:1
valueAccessor @ tko.js:1
r @ tko.js:1
(anonymous) @ tko.js:1
```

**Comment by caseyWebb** [comment]
is `value` an observable? if so you need to unwrap, `checked: $parent.Settings.values[value()]`. Can you show your view model?

**Comment by tresayle** [comment]
Thank you **caseyWebb**
