### ISSUE TITLE
Support for {{#else}} ?

### ISSUE THREAD

**Issue by davetropeano** [knockout/tko#13]
I might be misinterpreting the release notes but I cannot get `{{#else}}` to work and assumed (lol) that since the virtual binding for `else` was added a punches-like equivalent would come for "free"

Here's the broken example:

[JSBin](http://jsbin.com/caxewu/edit?html,js,console,output)

Using the  `{{#if}} / {{#ifnot}}` works. I tried an `{{#else}} {{/else}}` block but that didn't work as well.

**Comment by brianmhunt** [comment]
Hi Dave - operating on mobile so hard to type this out 😀 but there are two options for else.  One is using `<!-- else -->` inside an if/unless/ifnot binding (no #), the other is having a "peer" {{#else}} binding.  I can't see the example on my phone but I hope this gives you something to go on. :)

**Comment by brianmhunt** [comment]
... in any case please leave this open as I'd like to put an example in the docs!

**Comment by davetropeano** [comment]
1. I had to clean up my markdown comment with the correct link to JSBin.
2. Here's the code snippet I'd like. The basic pattern (to me) is that for every control-y virtual binding we should have an equivalent {{#}}

```html
  <ul>
    <li>Home</li>
   
    {{#if loggedIn}}
    <li><a href="#">New Request</a></li>
    <li><a href="#">Trips</a></li>
    <li><a href="#" data-bind="click: logout">logout</a></li>
    {{#else}}
    <li><a href="#" data-bind="click: login">login</a></li>
    {{/if}}
  </ul>
```

**Comment by mbest** [comment]
It needs to be like this

    {{#if loggedIn}}
    <li><a href="#">New Request</a></li>
    <li><a href="#">Trips</a></li>
    <li><a href="#" data-bind="click: logout">logout</a></li>
    {{/if}}
    {{#else}}
    <li><a href="#" data-bind="click: login">login</a></li>
    {{/else}}

**Comment by brianmhunt** [comment]
I've updated the if-binding documentation, here: http://www.tko.io/a/if-binding.html

The alternative to two `{{#...}}` blocks is to use `<!-- else -->` like this:

```
<ul>
    <li>Home</li>
   
    {{#if loggedIn}}
    <li><a href="#">New Request</a></li>
    <li><a href="#">Trips</a></li>
    <li><a href="#" data-bind="click: logout">logout</a></li>
    <!-- else -->
    <li><a href="#" data-bind="click: login">login</a></li>
    {{/if}}
</ul>
```

Ideally we'd have support builtin for a mustache equivalent e.g. `{{ else }}`, and have the `{{# else }}` binding check to see if it's already inside an `if` binding so cases like you've highlighted above with `{{# if ... }}...{{# else }}...{{/ if }}` would behave as expected.

**Comment by brianmhunt** [comment]
Closing this as the solution is discussed, but we can re-open if there's something to add, here.
