### ISSUE TITLE
Add preventDefault to event handler options

### ISSUE THREAD

**Issue by danieldickison** [knockout/tko#147]
Because lambda (arrow functions) in bindings currently only support a single expression, the old pattern of returning `true` from a (e.g.) click handler is a bit inconvenient:
```
data-bind="click: function (event) {
    setSomeValue('foo');
    return true;
}"
```

Adding a `preventDefault` key to an event handler was discussed in #32 but it doesn't appear to have been implemented. Does this still sound like a good idea?

```
data-bind="click: {
    handler: (event) => setSomeValue('foo'),
    preventDefault: false
}"
```

**Comment by brianmhunt** [comment]
@danieldickison I think this scratches an itch a few people will have. 😀

**Comment by maskmaster** [comment]
Using a helper-function like
```html
data-bind="click: utils.preventDefault(event => setSomeValue('foo'))"
```
would be a more terse variant. The exact semantics from knockout could in this case be retained.

Of course, if `preventDefault` needs to be observable we might need to do it like
```html
data-bind="click: event => { setSomeValue('foo')); return $data.shouldPreventDefault; }"
```

A third alternative, and in my opinion more semantically correct, is to create your own binding handler "capturedClick" or something like that, where you describe the functionality instead of implementing/open-coding it in the view.

**Comment by tscpp** [comment]
Isn't this what we have a viewModel for? Also, what about stopPropagation() and stopImmediatePropagation()?

**Comment by brianmhunt** [comment]
I tend to think there are two "correct" solutions here.

#### 1. The best option for a system where you know what you need and have total control is what @maskmaster suggested:

> A third alternative, and in my opinion more semantically correct, is to create your own binding handler "capturedClick" or something like that, where you describe the functionality instead of implementing/open-coding it in the view.

No library changes would be needed for this.

#### 2. a preferable option for a "drop-in" pre-built library, when experimenting (e.g. before knowing _what_ works), or behavioural visibility is better in the binding, can be to have a parameterized system...as @tscpp noted:

> Also, what about stopPropagation() and stopImmediatePropagation()? These functions and preventDefault() is functions, not options.

in which case `stopPropagation` and `stopImmediatePropagation` ought to be parameters in the library as well.

There's nothing stopping folks from using a function e.g. `utils.preventDefault` but that doesn't require any library changes.

**Comment by brianmhunt** [comment]
Closing this as I trust it's closed, but we can always re-open if there's more to discuss here.
