### ISSUE TITLE
Set up Greenkeeper for dependency tracking

### ISSUE THREAD

**Issue by brianmhunt** [knockout/tko#18]
https://greenkeeper.io/

**Comment by brianmhunt** [comment]
Closing this for now as Greenkeeper has limited benefit for monorepos

**Comment by caseyWebb** [comment]
I may be mistaken, but I think this may be resolved with [Yarn workspaces](https://yarnpkg.com/blog/2017/08/02/introducing-workspaces/) and [greenkeeper-lockfile](https://github.com/greenkeeperio/greenkeeper-lockfile) together.
