### ISSUE TITLE
Merges from mainline

### ISSUE THREAD

**Issue by brianmhunt** [knockout/tko#2]
This issue is just to link commits from knockout that ought to also be merged here.

**Comment by brianmhunt** [comment]
knockout/knockout#1975 https://github.com/knockout/knockout/commit/eb880656a8daf698d4fd56e15f2f82ba89ca1d9d

knockout/knockout#1974

**Comment by mbest** [comment]
Don't think this was meant to be closed

**Comment by brianmhunt** [comment]
Weird.  Must've been by the commit message.  Thanks.

**Comment by brianmhunt** [comment]
I'd say this is a dupe of #5, so closing
