### ISSUE TITLE
Array.isArray should return true for an `observableArray`

### ISSUE THREAD

**Issue by brianmhunt** [knockout/tko#29]
This means we probably have to add an Array instance to the observableArray prototype chain.

**Comment by mbest** [comment]
Observables already have `Function` at the end of the prototype chain.

**Comment by brianmhunt** [comment]
Thanks @mbest - I think we will have to experiment with an array instance as an intermediary on the prototype chain, if it can't go at the end

**Comment by futpib** [comment]
@brianmhunt I believe what you want to do is indeed impossible to achieve for the reason @mbest mentioned. At least at the current state of JS.

You can make `observableArray` (iterable)(https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Iteration_protocols) thought.

**Comment by brianmhunt** [comment]
Closing this as impossible. Noting that observableArray is now iterable for tko.
