### ISSUE TITLE
<!-- else --> is the only special comment that does not start with "ko"

### ISSUE THREAD

**Issue by futpib** [knockout/tko#31]
Other than just being a bit inconsistent, this might pose (minor) inconveniences when you want to process ko-powered templates with [HTMLMinifier](https://github.com/kangax/html-minifier) specifying [ignoreCustomComments](https://github.com/kangax/html-minifier#options-quick-reference) regex option.

**Comment by krnlde** [comment]
I don't see your point: https://www.npmjs.com/package/knockout-else

Documentation says `<!-- ko else -->` as expected.

**Comment by futpib** [comment]
Sorry, didn't notice that `ko else` is also supported.

**Comment by brianmhunt** [comment]
I can see why there'd be confusion here.   As a matter of history, the `else` binding came long before tko's `if` binding was updated to support an inline `<!-- else -->`
