### ISSUE TITLE
Request: support for passive events

### ISSUE THREAD

**Issue by krnlde** [knockout/tko#32]
[Passive event listeners](https://developers.google.com/web/updates/2016/06/passive-event-listeners), especially for the mouse `wheel` event, have landed and established in [most](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#Browser_compatibility) of the major browsers by now. We should consider adopting that into the `event` binding-handler. I suggest an API like that:

```html
<div data-bind="event: {wheel: {handler: handleWheel, passive: true}}"></div>
```
or shorter, but less generic:

```html
<div data-bind="passiveEvent: {wheel: handleWheel}"></div>
```

@brianmhunt, thoughts?

**Comment by brianmhunt** [comment]
Good idea, thanks for suggesting.

I like the short hand (`passiveEvent` binding handler) and 

```html
<div data-bind="event: {wheel: handleWheel, passive: true}"></div>
```

Of course we get a name collision of `passive`...  Will think about that. :)

**Comment by krnlde** [comment]
Look again :) no conflict, since the value for `wheel` is an object.

**Comment by brianmhunt** [comment]
I feel like there's too much room for spelling errors, too much typing, and too many brackets in the more generic version.  I'd like to also include some sort of `capture:true` option, and maybe `stopPropagation` and `preventDefault`.

Some suitable syntaxes might be (for passive + capture):

```html
<div data-bind='event: {wheel+passive+capture: handleWheel}'></div>
<div data-bind='event.wheel+passive+capture: handleWheel}'></div>
<div data-bind='event.wheel: handleWheel+passive+capture}'></div>

<!-- or, adding all options -->
<div data-bind='event.wheel: handleWheel+passive+capture+preventDefault+stopPropagation}'></div>
```

How does that look / feel?

A new syntax, absent rewriting for KO3, will not be backwards compatible.

**Comment by krnlde** [comment]
This doesn't look like valid JS. For me the charme of knockout's `data-bind` is the appearance of natural JS objects inside the attribute value, and I would want to keep that. Concidering your answer I would suggest `eventPassive: ...` as a bindingHandler, since it doesn't provoke spelling errors (at least not more than the ordinary `event` handler would do), and it is meaningful.

**Comment by brianmhunt** [comment]
Yeah, that's a good point. 

The issue with `passiveEvent` is that it doesn't work for a larger set of options e.g. passive + capture: `eventPassiveCapture`? 

It might be that the correct way is, as you suggested, the `wheel: {handler: wheelHandler, passive: true, capture: false}`.

Mulling it. :)

**Comment by krnlde** [comment]
> It might be that the correct way is, as you suggested, the wheel: {handler: wheelHandler, passive: true, capture: false}.

Probably :-/
Your only objection would be the error-prone-ness (e.g. typos)?

**Comment by brianmhunt** [comment]
This will be in beta-1
