### ISSUE TITLE
Choose a system for docs / documentation

### ISSUE THREAD

**Issue by brianmhunt** [knockout/tko#36]
We need a way to assemble the documentation into a static site.

e.g. https://github.com/lord/slate

**Comment by krnlde** [comment]
We considered the metalsmith approach: http://www.metalsmith.io/

**Comment by brianmhunt** [comment]
Thanks @krnlde  — After mulling options and having some familiarity with the options I've decided on pug + markdown-it, with CodePen for examples, as in #41 .  We'll see how it goes. :)
