### ISSUE TITLE
Components should be case insensitive 

### ISSUE THREAD

**Issue by brianmhunt** [knockout/tko#43]
Per https://twitter.com/vekzdran/status/924209856059502592

**Comment by vmandic** [comment]
A short momentary recall is that I could not use <someCustomEl /> but could use <some-custom-el>. Again now from my memory... I did not even face an error in the console. Using the custom data-bind and component binding worked!

**Comment by brianmhunt** [comment]
Thanks @vmandic — it turns out custom elements need a dash (`-`) e.g. `some-custom-el` will work but `somecustomel` will not, which is IIRC a W3C thing.  Will check for this and throw in tko.
