### ISSUE TITLE
Any other forward-ports

### ISSUE THREAD

**Issue by brianmhunt** [knockout/tko#50]
@mbest / @knockout/core / @knockout/extended  Does anyone see anything committed to Knockout 3.x line that's not been forward-ported?

1. after-render / childrenComplete
2. foreach update knockout/knockout#2324
3. any other plugins (e.g. your `switch/case` plugin)

**Comment by mbest** [comment]
I thought I might see what's "missing" by running the latest Knockout tests against TKO, but there are a lot of failures. Any thoughts?

**Comment by brianmhunt** [comment]
Thanks @mbest. That is an interesting methodology. I imagine there would be a lot of false negatives with that, as I had to manually modify about half the tests, but it still might give some insight. 

If you are set up for it, can you generate a list of the tests that fail? Then I can manually compare.

It might also be useful to compare the total list of tests.

**Comment by mbest** [comment]
[Failing 236 specs.docx](https://github.com/knockout/tko/files/1585251/Failing.236.specs.docx)

**Comment by mbest** [comment]
I "fixed" a bunch of tests by updating `useMockForTasks`. Here's what's left.

[Failing 162 specs.docx](https://github.com/knockout/tko/files/1585275/Failing.162.specs.docx)

**Comment by brianmhunt** [comment]
Thanks @mbest 👍

**Comment by mbest** [comment]
Merry Christmas!

[Failing 161 specs details.docx](https://github.com/knockout/tko/files/1586064/Failing.161.specs.details.docx)

Here's with the actual errors.

**Comment by brianmhunt** [comment]
Awesome - very helpful! Thanks and merry Christmas 🎅

**Comment by brianmhunt** [comment]
In #54 I've added the latest Knockout specs to the monorepo, as part of a `knockout` package in `packages/knockout`.

Gotten it down to 135 failing tests.

**Comment by mbest** [comment]
That's cool!

**Comment by brianmhunt** [comment]
Down to around 37 failing tests, most related to the foreach or the async children binding completion.

**Comment by brianmhunt** [comment]
Subject to #68 and #69 #70 and comments and anything that fell through the cracks, I'm closing this as it appears complete.
