### ISSUE TITLE
Merging new data with old

### ISSUE THREAD

**Issue by IPWright83** [knockout/tko#52]
One of the drawbacks I've found when using Knockout is when significant portions of a viewModel change as a result of something it is quite difficult to update. My particular example involved changing about 8/9 deeply nested objects (a few of which had observables within them).

I wonder if having some functions to merge a a POJO with an existing objects observables (viewModel) would be helpful / in scope for this project.

**Comment by caseyWebb** [comment]
Duplicate of #45

Use http://knockoutjs.com/documentation/plugins-mapping.html or https://github.com/Profiscience/knockout-contrib/tree/master/packages/utils.merge. The former is widely used and more powerful, the latter is orders of magnitude faster.

A mapping function should probably exists in Knockout/TKO though.

**Comment by brianmhunt** [comment]
@IPWright83 Performance wise, deferred updates can yield dramatic improvements in some scenarios.

**Comment by IPWright83** [comment]
@caseyWebb Thanks - I can see your `utils.merge` offering an example usage of updating an existing observable. I wasn't aware that it was even possible with the `mapping` plugin which I've used a number of times in the past.

@brianmhunt yeah that's true, though in my case probably not an issue. That might be something to build into the `mapping` plugin to offer a defer flag on it.
