### ISSUE TITLE
Add `modify` function to observables`

### ISSUE THREAD

**Issue by brianmhunt** [knockout/tko#59]
@knockout/core @caseyWebb   I'm planning on adding a "modify" function to `subscribable.fn`, like this:

```javascript
Object.assign(subscribable.fn, {
  modify (fn, peek) {
    this(fn(peek ? this.peek() : this()))
  }
})
```

I'm sure this'll be useful for thing like e.g. incrementing `obs.modify(x => x + 1)`, changing case `obs.modify(x => x.toUpperCase())`.

How does the name `modify` work?  Are there any similar APIs whose naming convention we might borrow?  Nothing came to mind so I thought I'd ask.

Does the function itself seem to capture the essence?

**Comment by caseyWebb** [comment]
I think `modify` or `mutate` would be clear

**Comment by mbest** [comment]
I suggest that `peek` be the default.

**Comment by brianmhunt** [comment]
@mbest Thanks, I was thinking that too.

**Comment by avickers** [comment]
This brings something else to mind for me: validation functions.  Right now there are plugins for knockout to do this for various form elements, but it would be kind of nice to have a first class sanity checking that prevents bad updates whether they come from either user input or corrupted model data being loaded, and then triggers some event/throws some error that can be handled according to context.

**Comment by brianmhunt** [comment]
@avickers Yes, I've built that for personal work and I've some thoughts about how it could be done more generally — since we're moving into ko 4 beta, I feel like would be appropriate for ko 4.1, alongside a proper first-class router in the default/reference build.
