### ISSUE TITLE
Up for grabs?

### ISSUE THREAD

**Issue by Sebazzz** [knockout/tko#61]
I love knockout and love to contribute to the next generation of Knockout. Is there room in the project to contribute?

**Comment by brianmhunt** [comment]
Absolutely, @Sebazzz, thanks for reaching out .  Did you have anything in mind?

**Comment by Sebazzz** [comment]
Good to hear. I'm not sure what readily tasks are available and what is required for them (for instance: are they thought out, or still need design, need additional reviewing etc).

**Comment by brianmhunt** [comment]
@Sebazzz Thanks - the typescript support is one area where help would be valuable.

I've started a project https://github.com/knockout/tko/projects/2 to keep track of the high-level issues before a beta release.

Once we reach beta, we can start looking at all the additional features and API updates.  The plan would be to have another release not too long after we're satisfied with KO 4, with a number of the in-demand additional features & updates.

Being volunteer-only, it's going to take a while, but we'll get there. :)

**Comment by brianmhunt** [comment]
If there's any areas where you're comfortable contributing, please don't hesitate to let us know.  I'm happy to have a call discussing it, too, if you think that'd help.

**Comment by brianmhunt** [comment]
That's super-weird; thanks for trying/sorting that out, @Sebazzz .  Please share if there's any workarounds we can build in.

**Comment by Sebazzz** [comment]
Deleting the symlink, ignoring node_modules appears to work. What is the purpose of that symlink?

**Comment by brianmhunt** [comment]
I presume it was there so that there would be some node resolution that otherwise didn't work.

It may have already been resolved with yarn & lerna.

We can remove and if needed try another workaround.

**Comment by brianmhunt** [comment]
Closing this, unless there's more to discuss/suggest here.
