### ISSUE TITLE
arrayFirst returns undefined if found value is falsy

### ISSUE THREAD

**Issue by mbest** [knockout/tko#63]
For example, `""`, `0`, `null`.

https://github.com/knockout/tko/blob/4f302f55d075bacad8ece3b440f0803aa95e6574/packages/tko.utils/src/array.js#L22

**Comment by brianmhunt** [comment]
Thanks @mbest ; that seems a. clearly the wrong behaviour here, and b. like something I would have done in response to some tests failing.  Will look into it.
