### ISSUE TITLE
Use `<ko ...>` for virtual elements

### ISSUE THREAD

**Issue by brianmhunt** [knockout/tko#75]
Since JSX doesn't allow comments, I'm adding support for a new element-type:

```html
<ko binding='value'></ko>
```

becomes, in preprocessing

```html
<!-- ko binding: value --><!-- /ko -->
```

**Comment by mbest** [comment]
For completeness:

`<ko binding1='value1' binding2="value2"></ko>`

becomes, in preprocessing

`<!-- ko binding1: value1, binding2: value2 --><!-- /ko -->`
