### ISSUE TITLE
Question: Is it possible access the latest alpha's separate modules today?

### ISSUE THREAD

**Issue by ryansolid** [knockout/tko#81]
I've been playing around trying to just get the computed/observable modules but I haven't had any luck getting the latest, and seems older versions pre mono repo and npm are all mismatched with each other.

I've been writing a pre-compiled renderer based on Knockout's core that I've seen really positive results on (Currently 5th fastest framework on [JS Framework Benchmark](https://github.com/krausest/js-framework-benchmark) right behind Inferno). It's clear bringing in all of KO 3.4.2 is really the limiting factor(compare with KO 3.4.1 on the opposite end of the table) so I wanted to start testing this if the core is starting to get solid.

**Comment by brianmhunt** [comment]
Hi @ryansolid — Thanks so much for checking it out. That's something I'm working on imminently — it'll all be under the @tko npm organization (which we got just last week) and I'll put some new docs up.

I'll ping here when it's up (aiming for this weekend)!

Cheers

**Comment by ryansolid** [comment]
Sounds good. Thanks.
