### ISSUE TITLE
Patreon

### ISSUE THREAD

**Issue by avickers** [knockout/tko#83]
@brianmhunt have you been getting my contributions?  I might have done it anonymously, if that was possible, and forgotten but I have receipts going back to March.  (Signing in didn't really clear this up for me.  Their UX leaves much to be desired.)  I want to make sure that I'm not throwing money into a black hole.

**Comment by brianmhunt** [comment]
It is indeed arriving, thank you @avickers.  I've updated the `Backers.md` file. Turns out that the reporting side of Patreon leaves a little to be desired too :grin:   Thank you so much for your contribution, it really helps!
