### ISSUE TITLE
will useOnlyNativeEvents be on by default in TKO?

### ISSUE THREAD

**Issue by nebulousdog** [knockout/tko#84]
it would be nice if `useOnlyNativeEvents` is on by default in TKO, or that jQuery isnt a peer dependency in any way. Cheers!

**Comment by martonx** [comment]
jQuery isn't dependency for knockout :)

**Comment by brianmhunt** [comment]
Agree.  It may be on by default for the knockout build, but for the tko build I'll try to ensure native events are preferred.

**Comment by nebulousdog** [comment]
awesome, thanks @brianmhunt
