### ISSUE TITLE
Fix, document, or remove broken Sauce Labs CI

### ISSUE THREAD

**Issue by yjo** [knockout/tko#89]
Currently the GitHub project readme embeds a scary red grid of failing tests on Sauce Labs.  Following the link takes me to https://saucelabs.com/u/tko where I can see lots of failing tests (but nothing since June). 
Additionally, I can't find any way to drill down to see the actual test failures - not sure if that's a Sauce Labs issue or just locked down permissions.

As someone who hasn't been closely following the TKO project, it's not clear to me if the Sauce Labs CI is out of date and should be ignored, is reflecting some known limitations in functionality / browser compatibility, or is showing something worse.

Assuming the project isn't actually in a 'very broken' state, could you fix, document, or remove the broken Sauce Labs tests to avoid putting people off unnecessarily?

**Comment by brianmhunt** [comment]
Thanks @yjo; will do
