### ISSUE TITLE
knockout.punches throwing error

### ISSUE THREAD

**Issue by jlaustill** [knockout/tko#9]
Just dropping ko.js in place of knockout.js(3.4.0) I'm getting an error with knockout.punches.  It looks like this

knockout.punches.js:60 Uncaught TypeError: Cannot read property 'preprocessNode' of undefined(…)addNodePreprocessor 
@ knockout.punches.js:60enableInterpolationMarkup 
@ knockout.punches.js:525ko_punches.enableAll 
@ knockout.punches.js:99(anonymous function) 
@ main.js:81runCallbacks 
@ domReady.js:24callReady 
@ domReady.js:35pageLoaded 
@ domReady.js:50

Is there another version of punches?  Every project I have literally uses punches as my html template engine, so I can't really test without it without starting a new project from scratch :)

**Comment by brianmhunt** [comment]
Thanks for the report 😀

Tko incorporates punches already so you should simply be able to remove the reference to the separate punches file.

Let me know if that solves the issue.

Cheers

**Comment by jlaustill** [comment]
Oh wow!  Sorry!  That's actually quite awesome, though.  

After removing the punches file and calls my site seems to be working for the most part.  I have one error with a valueAccessor not being a function in one custom binding, but other than that the site is WAY more responsive.  

I'll dig into that error tomorrow, might just be me writing a dumb binding, this is one I wrote years ago when I didn't have a clue lol.
