### ISSUE TITLE
Beta 1) Postbox or a SSoT?

### ISSUE THREAD

**Issue by avickers** [knockout/tko#93]
I have some reservations about including Postbox in the core library.  The succinct version is that I believe that, in 2019, it's pretty clearly an anti-pattern.

Knockout is MVVM, right?  To date, Knockout has really only cared about the the V and VM.  As far as the core library, I think that that should continue; however, I really think that Knockout would benefit from studying the lessons of Flux and Vuex.

All business logic and definitive state should be maintained in the model.  Postbox encourages a sort of spaghetti code architecture where it ends up federated among view models.  That causes a lot of problems at scale, which any discussion of Flux or Vuex will highlight.
 
A lot of the complaints about performance that I saw in the Google Groups ultimately came down to people performing business logic in their VMs, and not using an M at all.  It's kind of our fault, too; it's not covered in the documentation.  The documentation basically assumes that people understand the MV* paradigm pretty well, but the truth is that, in the age of frameworks, people don't really stop and think about/teach the patterns anymore.  IMO, TKO should aspire to be structured in such a way that it encourages adherence to MVVM rather than enable bad habits.

I always designed my knockout apps with multiple views with a Single Source of Truth, and I refused to make any Ajax calls or requests to the backend from anywhere else.  I really think it's good form to prioritize VM <--> M rather than VM <--> VM.

**Comment by brianmhunt** [comment]
I completely agree, and it's been on my mind for some time. I'm going to take it out but leave it available as a plugin.  It's clearly an anti-pattern in the modern design methodologies.

**Comment by avickers** [comment]
Sure, it can absolutely be used responsibly by people that know what they're doing.  I'll ponder on alternatives.

One step closer to Beta then! 🎉
